#!/usr/bin/env python3
"""Render the world-view route OUT OF GAME, to a PNG.

WHY THIS EXISTS. Every look decision on the route -- feather, halo weight, the near
fade, opacity, colour -- has so far cost a launch, a load, a walk to a quest giver and
a squint. That loop is minutes long and the thing being judged is a few dozen pixels,
so the comparisons that matter (this feather against that one, side by side, on the
same ground) were never actually made: each session judged one setting against a
memory of the last.

This draws the same sprites the game draws, from the same textures and the same
constants, onto a synthetic floor. It is a LOOK tool, not a correctness tool -- the
harnesses (tools/nav-harness, tools/route-harness) own behaviour, and nothing here
should ever be used to decide whether the route is right, only whether it reads.

WHAT IS REPRODUCED EXACTLY, because it is read from the source rather than retyped:

  * every RTE constant (opacity, colour, widths, feather pad, halo, fades, clamps) is
    parsed out of gamedata/scripts/iqm_core.script at run time;
  * the vertex spacing rules (SEG_DIV / SEG_MIN / SEG_MAX / TURN_TOL) are parsed out
    of iqm_nav.script;
  * the TEXTURES are generated by importing tools/stroke-tex/build.py and calling its
    own alpha functions, so the artwork is the shipped artwork -- and `--feather`
    re-runs them at a different value without touching the shipped assets, which is
    the whole point of the tool;
  * the drawing rules are ported line for line from IqmCards: seg_width measures the
    thickness from the segment's own projected ground edges, place_strip builds the
    rect in UI units and rotate-then-uniform-scales it, the halo is the same texture
    at a larger rect, and everything is composited far to near in the same order.

WHAT IS AN APPROXIMATION, stated plainly so nothing is read off this that shouldn't be:

  * THE PROJECTION. The game calls game.world2ui_with_depth (engine side, and it takes
    the player's actual FOV); this is a pinhole camera at --fov degrees vertical. So
    absolute on-screen sizes depend on a number we are assuming. RELATIVE judgements --
    is this edge softer than that one, does the near mark dominate -- do not.
  * THE FLOOR is procedural concrete, not a level. It exists to have something to be
    legible against, and carries a light patch and a dark one on purpose, because the
    route has to work on both.
  * FILTERING. PIL's bilinear resample where the GPU has its own; at these scales the
    difference is well under the effects being judged.
  * No occlusion. Every point is drawn lit, as if nothing were in the way.

Usage:
    python preview.py                          # default look, band style
    python preview.py --style arrows --scene bend
    python preview.py --compare                # current vs the sharpened proposal
    python preview.py --feather 0.04 --hmin 0.75 --head 1.5 --alpha 255
    python preview.py --dump                   # print every parsed constant and exit

Requires Pillow. Run from anywhere; paths are resolved off this file.
"""
import argparse
import importlib.util
import math
import os
import random
import re
import sys

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
MARKERS = os.path.join(ROOT, "gamedata", "scripts", "iqm_core.script")
NAV = os.path.join(ROOT, "gamedata", "scripts", "iqm_nav.script")
STROKE_TEX = os.path.join(ROOT, "tools", "stroke-tex", "build.py")

# The virtual UI space every static is placed in -- the same 1024x768 the mod uses.
UI_W, UI_H = 1024, 768

# How much of a segment's own LENGTH the joint overlap may take, under --joint capped.
# A bend of angle t needs about (th/2) * tan(t/2) of extension to close its wedge, and
# iqm_nav sizes segments so consecutive ones turn by ~1/7 radian -- about 4% of a
# half-thickness. So a third of the segment is still enormously over-provisioned, and
# far enough from the shipped `th` at the near end to show whether the ladder is really
# the overlap.
JOINT_FRAC = 0.35


# --------------------------------------------------------------------------
# Reading the real constants
# --------------------------------------------------------------------------
# Parsed rather than copied. A preview whose numbers have drifted from the game's is
# worse than no preview at all: it answers confidently and wrongly, and nothing about
# the picture says which constants it used. --dump prints them for the same reason.
# Only what the one surviving design uses. The stroke's and the billboard's constants
# (ww, bandw, SEGS, REF, MIN, MAX, HALO...) went with the four styles dropped in R2.26c.
RTE_KEYS = """a r g b alen awide aw FPAD WMIN WMAX MCAP EDGE EDGE_MIN EDGE_MAX SHA
              HEAD HMIN MNEAR MFADE MLMIN PPM FADE TAIL""".split()

NAV_KEYS = ["SEG_DIV", "SEG_MIN", "SEG_MAX", "TURN_TOL", "PATH_STEP", "ARROW_LIFT",
            "NEAR_TRIM", "TRIM_FRAC", "MAX_DRAW", "MAX_CHEV", "CHEV_DIR"]


def _read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def parse_rte():
    """Pull the RTE table's numeric fields out of iqm_core.script.

    Whitelisted by name rather than taken wholesale: the table also holds NAMES,
    the CLIP grid and the t1/t2 scratch points, and a blind `key = number` sweep
    would pick up `x = 0, y = 0, z = 0` from the scratch and call it geometry.
    """
    src = _read(MARKERS)
    start = src.index("local RTE = {")
    # To the table's own closing brace, not a fixed byte count. A 12000-char window was
    # enough until R2.31's comment pushed PPM past it, and the failure was a preview that
    # could not start rather than one that quietly read the wrong number -- but only by
    # luck, since the window's far end lands wherever the prose happens to reach.
    end = src.find("\n}", start)
    body = src[start:end if end > start else start + 20000]
    out = {}
    for key in RTE_KEYS:
        m = re.search(r"\b" + key + r"\s*=\s*(-?\d[\d.]*)", body)
        if not m:
            raise SystemExit("preview: could not find RTE.%s in iqm_core.script" % key)
        out[key] = float(m.group(1))
    # The MCM default colour, which read_config pushes over RTE's own initialiser. The
    # table in RTE is the fallback for a missing option, not what the player sees.
    for key in ("route_r", "route_g", "route_b", "route_a", "route_w", "route_gap",
                "route_size"):
        m = re.search(r"\b" + key + r"\s*=\s*(\d+)", src[:20000])
        if m:
            out[key] = float(m.group(1))
    return out


def parse_nav():
    src = _read(NAV)
    out = {}
    for key in NAV_KEYS:
        m = re.search(r"^local " + key + r"\s*=\s*(-?\d[\d.]*)", src, re.M)
        if not m:
            raise SystemExit("preview: could not find %s in iqm_nav.script" % key)
        out[key] = float(m.group(1))
    return out


def load_builder():
    """Import tools/stroke-tex/build.py for its alpha functions.

    Importing rather than reimplementing: `across`, `along` and `mark_alpha` ARE the
    artwork, and a second copy of them here would be a second thing to keep in step.
    Safe to import -- everything that shells out to ImageMagick is inside main().
    """
    spec = importlib.util.spec_from_file_location("iqm_stroke_build", STROKE_TEX)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    # Snapshot the SHIPPED values before anything renders. tex_strip/tex_mark set
    # mod.FEATHER to whatever is being previewed -- that is how --feather works -- so
    # after the first render the module no longer knows what the assets on disk were.
    # Reading it back later is how the comparison sheet first labelled the CURRENT panel
    # with the PROPOSED feather, which is the one mistake a look tool must not make.
    mod.SHIPPED = {"FEATHER": mod.FEATHER, "ARM_TIP": mod.ARM_TIP, "ARM_TAIL": mod.ARM_TAIL}
    return mod


# --------------------------------------------------------------------------
# Textures
# --------------------------------------------------------------------------
def tex_strip(bp, feather, tip=0.0, tail=0.0):
    """iqm_stroke / iqm_arm, at an arbitrary feather. Mirrors build.build()."""
    bp.FEATHER = feather
    w, h = bp.W, bp.H
    img = Image.new("RGBA", (w, h), (255, 255, 255, 0))
    px = img.load()
    for y in range(h):
        c = bp.across(y)
        for x in range(w):
            px[x, y] = (255, 255, 255, int(round(255 * c * bp.along(x, tip, tail))))
    return img


def tex_mark(bp, feather, size=192):
    """iqm_mark, at an arbitrary feather. Mirrors build.build_mark()."""
    bp.FEATHER = feather
    x0, x1, y0, y1 = bp.mark_box()
    hl, hw, ha = bp.MARK_LEN * 0.5, bp.MARK_WIDE * 0.5, bp.MARK_ARM * 0.5
    pad = feather * bp.MARK_ARM
    img = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    px = img.load()
    for j in range(size):
        yy = y0 + (j + 0.5) / size * (y1 - y0)
        for i in range(size):
            xx = x0 + (i + 0.5) / size * (x1 - x0)
            av, ink = bp.mark_alpha(xx, yy, hl, hw, ha, pad, want_ink=True)
            v = int(round(255 * ink))
            px[i, j] = (v, v, v, int(round(255 * av)))
    return img


# --------------------------------------------------------------------------
# Candidate LOOKS (preview only -- these draw no assets and ship nothing)
# --------------------------------------------------------------------------
# R2.33's screenshot: the geometry lands, and the marks still read as printed ON the
# image rather than painted on the floor. Four things are being asked here, and each is
# a change to the TEXTURE rather than to the renderer, which is why they can be tried
# without touching a shipped constant.
#
#   wear      the interior is one flat alpha, which is the vinyl-sticker tell. Real floor
#             paint is broken -- thin over aggregate, worn where boots go.
#   rim       MARK_RIM is 0.09 of an arm and does not read at all in game.
#   rim_ink   the rim is ink 0, i.e. pure black whatever the route colour, which reads as
#             a hole punched in the glyph rather than a shaded lip.
#   shadow    nothing seats the mark on the ground. It cannot be a second widget (R2.31:
#             a scaled copy of an asymmetric glyph emerges on one edge only), but it CAN
#             be baked outside the outline at ink 0 -- black survives the tint, because
#             SetTextureColor multiplies.
# THE NOISE IS build.py's, not a second copy of it. The preview exists to show what a
# rebuilt texture would look like, and a wear pattern generated by different code would be
# a different pattern -- the one thing this sheet must not do is show grain the shipped
# atlas will not have. Only the AMOUNT is a knob here; bp.wear_field owns the pattern.


def tex_mark_look(bp, R, feather, wear=0.0, rim=None, rim_ink=0.0, body_ink=1.0,
                  shadow=0.0, shadow_w=None, size=256, seed=11):
    """The shipped chevron with any of the four look proposals applied.

    Everything still goes out in build.py's convention -- ink in RGB, coverage in alpha --
    because that is what survives SetTextureColor. The shadow is composited UNDER the
    paint here rather than drawn as a halo at render time, so what the sheet shows is what
    a rebuilt texture would give.
    """
    bp.FEATHER = feather
    if rim is not None:
        bp.MARK_RIM = rim
    hl, hw, ha = R["alen"] * 0.5, R["awide"] * 0.5, R["aw"] * 0.5
    pad = feather * R["aw"]
    # The halo's width in ground metres. mark_alpha's edge ramp reaches pad/2 OUTSIDE the
    # true outline, so passing a fat pad is exactly a soft dilation -- the shape's own
    # distance field, reused, rather than a blur of the picture.
    sw = shadow_w if shadow_w is not None else 0.75 * R["aw"]
    R["SPAD"] = (sw * 0.5) if shadow > 0 else 0.0
    back, fwd, half = shape_box("chevron", R)
    wm = bp.wear_field(size, seed) if wear > 0 else None
    img = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    px = img.load()
    for j in range(size):
        Y = -half + (j + 0.5) / size * (half * 2)
        for i in range(size):
            X = -back + (i + 0.5) / size * (back + fwd)
            av, ink = bp.mark_alpha(X, Y, hl, hw, ha, pad, want_ink=True)
            # THE KEYLINE, remapped at both ends. `ink` is 0 in the rim band and 1 inside,
            # and it MULTIPLIES the route colour, so the two ends are the rim's darkness
            # and the body's. Sliding rim_ink up gives a dark lip instead of a black hole;
            # pulling body_ink down below 1 inverts the whole device into a BRIGHT rim on
            # a slightly deeper body, which is the version that survives dark ground --
            # a black keyline on dark concrete is a black edge on a black floor.
            ink = rim_ink + (body_ink - rim_ink) * ink
            # Wear the paint, not the shadow -- a contact shadow is cast by the mark's
            # outline and does not flake with it.
            if wm is not None:
                # Thin where the noise dips below `thr` and nowhere else, so most of the
                # mark stays solid and the wear reads as scuffing rather than as a
                # texture laid over the whole glyph.
                t = max(0.0, (0.44 - wm[j][i]) / 0.44)
                av *= max(0.0, 1.0 - wear * t ** 1.1)
            if shadow > 0:
                h = bp.mark_alpha(X, Y, hl, hw, ha, sw) * shadow
                fa = av + h * (1 - av)
                ink = (av * ink) / fa if fa > 1e-6 else 0.0
                av = fa
            v = int(round(255 * ink))
            px[i, j] = (v, v, v, int(round(255 * av)))
    return img


# --------------------------------------------------------------------------
# Candidate SHAPES (preview only -- these draw no assets and ship nothing)
# --------------------------------------------------------------------------
# The keystone residual scales with how much DEPTH the glyph's footprint spans, and
# nothing else (R2.31). So the shape question is really a box question, and these exist
# to see what the two cheaper boxes actually look like before any of it is committed to
# build.py. `chevron` is the shipped artwork and comes from build.py as always.
#
#   arrow  a FILLED triangle -- same tip, no interior gap, so it needs no mitre
#          allowance and spans ~40% less depth than the chevron at the same width
#   bar    a plain rung across the path -- spans only its own thickness, which is the
#          least depth any mark can have while still being a mark
def shape_box(kind, R):
    """(back, fwd, half) in mark metres, the box the shape is drawn into and measured in."""
    hl, hw, ha = R["alen"] * 0.5, R["awide"] * 0.5, R["aw"] * 0.5
    # SPAD is the baked shadow's reach outside the outline, and it has to be in the BOX or
    # the halo is drawn outside the rect it was baked into -- i.e. cropped off. Zero
    # unless tex_mark_look put one there, so every other path is untouched.
    pad = R["FPAD"] * R["aw"] + R.get("SPAD", 0.0)
    if kind == "bar":
        return ha + pad, ha + pad, hw + pad
    if kind == "arrow":
        return hl + pad, hl + pad, hw + pad
    if kind in ("disc", "square"):
        # Equal in both axes on purpose: these two exist to show what a footprint with a
        # depth-to-width ratio of 1 costs. A rung's ratio is ~0.2, which is why it wins.
        r = hw * 0.55 + pad
        return r, r, r
    L = math.hypot(2.0 * hl, hw)
    return (hl + ha * hw / L + pad, hl + ha * L / hw + pad, hw + ha * 2.0 * hl / L + pad)


def tex_shape(kind, R, feather, size=192):
    """A convex candidate shape, in the same (ink in RGB, coverage in A) convention.

    Both are convex, so the signed distance is just the smallest distance to an edge --
    positive inside. That gives the feather and the inset keyline in one pass, the same
    two things build.mark_alpha computes for the chevron.
    """
    back, fwd, half = shape_box(kind, R)
    hl, hw, ha = R["alen"] * 0.5, R["awide"] * 0.5, R["aw"] * 0.5
    pad = feather * R["aw"]
    rim = 0.09 * R["aw"]                       # MARK_RIM, the baked keyline
    if kind == "disc":
        # Here to show what the ONE exactly-representable footprint costs when it is
        # fitted to its bounding box like everything else -- which is what the shipped
        # code would do, and is worse than any other candidate. The exact fit needs the
        # projected conic, not the box. See R2.31.
        r = half - pad
        img = Image.new("RGBA", (size, size), (255, 255, 255, 0))
        px = img.load()
        for j in range(size):
            Y = -half + (j + 0.5) / size * (half * 2)
            for i in range(size):
                X = -back + (i + 0.5) / size * (back + fwd)
                d = r - math.hypot(X, Y)
                a = max(0.0, min(1.0, d / pad + 0.5))
                a = a * a * (3 - 2 * a)
                ink = max(0.0, min(1.0, (d - rim) / pad + 0.5))
                ink = ink * ink * (3 - 2 * ink)
                v = int(round(255 * ink))
                px[i, j] = (v, v, v, int(round(255 * a)))
        return img
    if kind == "square":
        s = half - pad
        edges = [(1, 0, s), (-1, 0, s), (0, 1, s), (0, -1, s)]
    elif kind == "bar":
        edges = [(1, 0, ha), (-1, 0, ha), (0, 1, hw), (0, -1, hw)]   # |n.p| <= c
    else:
        # tip at (+hl, 0), base corners at (-hl, +/-hw): the base plus two long edges
        nx_, ny_ = 2.0 * hl, hw
        m = math.hypot(nx_, ny_)
        c = (2.0 * hl * hl + 0.0) / m          # distance from the origin to a long edge
        edges = [(-1.0, 0.0, hl), (nx_ / m, ny_ / m, c), (nx_ / m, -ny_ / m, c)]
    img = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    px = img.load()
    for j in range(size):
        Y = -half + (j + 0.5) / size * (half * 2)
        for i in range(size):
            X = -back + (i + 0.5) / size * (back + fwd)
            d = min(c - (nx * X + ny * Y) for nx, ny, c in edges)
            a = max(0.0, min(1.0, d / pad + 0.5))
            a = a * a * (3 - 2 * a)
            ink = max(0.0, min(1.0, (d - rim) / pad + 0.5))
            ink = ink * ink * (3 - 2 * ink)
            v = int(round(255 * ink))
            px[i, j] = (v, v, v, int(round(255 * a)))
    return img


# --------------------------------------------------------------------------
# Camera
# --------------------------------------------------------------------------
class Camera:
    """A pinhole stand-in for game.world2ui_with_depth.

    World is X/Z ground with Y up, as the game's is. The camera sits at eye height
    above the actor and looks along +X with a downward pitch -- i.e. what you see
    walking a route, which is the only view the route is ever judged in.
    """

    def __init__(self, eye=(0.0, 1.6, 0.0), pitch_deg=-12.0, yaw_deg=0.0,
                 vfov_deg=55.0, out_w=1280, out_h=720):
        self.eye = eye
        self.out_w, self.out_h = out_w, out_h
        p, y = math.radians(pitch_deg), math.radians(yaw_deg)
        # forward, right, up in world space
        self.fwd = (math.cos(p) * math.cos(y), math.sin(p), math.cos(p) * math.sin(y))
        self.right = (-math.sin(y), 0.0, math.cos(y))
        self.up = (-math.sin(p) * math.cos(y), math.cos(p), -math.sin(p) * math.sin(y))
        self.tan_half_v = math.tan(math.radians(vfov_deg) * 0.5)
        self.aspect = out_w / out_h
        # The engine's own aspect correction for rotated statics, from the same
        # expression iqm_core uses: (h/w) / (768/1024).
        self.ui_kx = (out_h / out_w) / (UI_H / UI_W)

    def project(self, x, y, z):
        """world -> (ui_x, ui_y, depth_sign). None when the point is behind the camera.

        Mirrors project_off's contract: the third value is a SIGN in the game (-1
        behind the camera), and callers only ever test `> 0`, so a depth is a
        strictly more informative thing to hand back that still satisfies them.
        """
        dx, dy, dz = x - self.eye[0], y - self.eye[1], z - self.eye[2]
        f = dx * self.fwd[0] + dy * self.fwd[1] + dz * self.fwd[2]
        if f <= 0.001:
            return None, None, -1.0
        r = dx * self.right[0] + dy * self.right[1] + dz * self.right[2]
        u = dx * self.up[0] + dy * self.up[1] + dz * self.up[2]
        ndc_x = (r / f) / (self.tan_half_v * self.aspect)
        ndc_y = (u / f) / self.tan_half_v
        return (ndc_x * 0.5 + 0.5) * UI_W, (0.5 - ndc_y * 0.5) * UI_H, f

    def dist(self, x, y, z):
        dx, dy, dz = x - self.eye[0], y - self.eye[1], z - self.eye[2]
        return math.sqrt(dx * dx + dy * dy + dz * dz)


# --------------------------------------------------------------------------
# The route geometry (iqm_nav's half)
# --------------------------------------------------------------------------
def scene_path(name, step, lift):
    """A dense point list, PATH_STEP apart, standing in for a solved A* route."""
    pts = []
    if name == "straight":
        n = int(70 / step)
        for i in range(n):
            pts.append((i * step, lift, 0.0))
    elif name == "bend":
        # 14 m out, a 90 degree turn rounded over a couple of metres (what smooth()
        # leaves), then away to the right. The corner is the case vertex placement
        # exists for, so it is the case worth looking at.
        d = 0.0
        while d < 14.0:
            pts.append((d, lift, 0.0))
            d += step
        for k in range(1, 13):
            t = k / 12.0
            ang = t * math.pi * 0.5
            cx, cz = 14.0, 3.0
            pts.append((cx + 3.0 * math.sin(ang) - 0.0, lift, cz - 3.0 * math.cos(ang)))
        d = 0.0
        while d < 45.0:
            pts.append((17.0, lift, 3.0 + d))
            d += step
    elif name == "curve":
        d = 0.0
        while d < 70.0:
            pts.append((d, lift, 6.0 * math.sin(d / 22.0)))
            d += step
    else:
        raise SystemExit("preview: unknown scene %r" % name)
    return pts


def build_draw_list(path, cam, nav, draw_m, gap_m, half_phase=False):
    """Port of iqm_nav.build_draw_list: vertices by turn/allowance, chevrons by arclength.

    Reduced to what the picture needs -- no cursor, no occlusion, no PHASE_ABS branch,
    and the trim comes straight from NEAR_TRIM (0 since R2.25) rather than being walked
    off a cursor. The vertex SPACING rule is the part that matters here, because it sets
    how thickness steps from one segment to the next.
    """
    seg_div, seg_min, seg_max = nav["SEG_DIV"], nav["SEG_MIN"], nav["SEG_MAX"]
    turn_tol, max_draw, max_chev = nav["TURN_TOL"], int(nav["MAX_DRAW"]), int(nav["MAX_CHEV"])

    def seg_allow(p):
        s = cam.dist(*p) / seg_div
        return max(seg_min, min(seg_max, s))

    start, trim = 0, 0.0
    trim_max = min(nav["NEAR_TRIM"], draw_m * nav["TRIM_FRAC"])
    while start < len(path) - 2:
        p = path[start]
        if cam.dist(*p) >= nav["NEAR_TRIM"]:
            break
        q = path[start + 1]
        seg = math.hypot(q[0] - p[0], q[2] - p[2])
        if trim + seg > trim_max:
            break
        trim, start = trim + seg, start + 1

    verts, vs = [path[start]], [0.0]
    chevs, cs = [], []
    # R2.25: the first chevron is ON the drawn start. HALF_PHASE adds one more at half a
    # gap (R2.33c), which is the near hole's actual shape: marks sit at k * gap from the
    # actor, so at the default spacing there is simply no paint between his feet and 3 m.
    sched = [0.0] + ([gap_m * 0.5] if half_phase else [])
    sched += [gap_m * k for k in range(1, max_chev + 2)]
    si = 0
    chev_at = sched[0]
    acc, vacc, turn = 0.0, 0.0, 0.0
    allow = seg_allow(path[start])
    emitted, last = start, start
    pdx = pdz = None

    for i in range(start + 1, len(path)):
        if len(verts) >= max_draw:
            break
        a, b = path[i - 1], path[i]
        dx, dz = b[0] - a[0], b[2] - a[2]
        seg = math.hypot(dx, dz)
        if acc + seg > draw_m:
            break
        if seg > 1e-4:
            ux, uz = dx / seg, dz / seg
            if pdx is not None:
                dot = pdx * ux + pdz * uz
                if dot < 1:
                    turn += 1 - dot
        if turn >= turn_tol or vacc + seg > allow:
            if emitted != i - 1:
                verts.append(path[i - 1])
                vs.append(acc)
                emitted, vacc, turn = i - 1, 0.0, 0.0
                allow = seg_allow(path[i - 1])
        if seg > 1e-4:
            while len(chevs) < max_chev and chev_at <= acc + seg:
                t = (chev_at - acc) / seg if seg > 1e-6 else 0.0
                chevs.append(((a[0] + dx * t, a[1] + (b[1] - a[1]) * t, a[2] + dz * t),
                              ux, uz, max(1, len(verts))))
                cs.append(chev_at)
                si += 1
                if si >= len(sched):
                    break
                chev_at = sched[si]
            pdx, pdz = ux, uz
        acc, vacc = acc + seg, vacc + seg
        last = i
    if len(verts) < max_draw and last > start and emitted != last:
        verts.append(path[last])
        vs.append(acc)
    return verts, vs, chevs, cs


# --------------------------------------------------------------------------
# The sprite layer (IqmCards' half)
# --------------------------------------------------------------------------
class Canvas:
    """Composites textured, tinted, heading-rotated rects the way the UI layer does.

    A heading-rotated static is built in UI units, rotated rigidly about its own
    centre, and only then scaled -- x by UI_KX and again by w/1024, which together are
    exactly h/768, the y factor (see place_strip). So the shape is rotate-then-
    UNIFORM-scale at h/768, while the rect's CENTRE is a position and takes the plain
    UI->screen map. Getting those two different is what makes a preview lie about
    every angle in the picture.
    """

    def __init__(self, base):
        self.img = base
        self.sc = base.size[1] / UI_H            # uniform shape scale
        self.px = base.size[0] / UI_W            # UI x -> screen px, for positions
        self.py = base.size[1] / UI_H

    def blit(self, tex, cx, cy, ln, th, ang, argb):
        a, r, g, b = argb
        if a <= 2:
            return
        w = max(1, int(round(ln * self.sc)))
        h = max(1, int(round(th * self.sc)))
        if w > 6000 or h > 6000:
            return
        spr = tex.resize((w, h), Image.BILINEAR)
        # tint: white artwork times the colour, alpha times the widget's own
        tr, tg, tb, ta = spr.split()
        spr = Image.merge("RGBA", (
            tr.point(lambda v: v * r // 255),
            tg.point(lambda v: v * g // 255),
            tb.point(lambda v: v * b // 255),
            ta.point(lambda v: v * a // 255)))
        spr = spr.rotate(math.degrees(ang), resample=Image.BICUBIC, expand=True)
        x = int(round(cx * self.px - spr.size[0] * 0.5))
        y = int(round(cy * self.py - spr.size[1] * 0.5))
        self.img.alpha_composite(spr, (x, y))


def seg_width(cam, pa, pb, ax, ay, bx, by, ww, wmin, cap):
    """Port of IqmCards:seg_width -- thickness measured from the ground edges."""
    dx, dz = pb[0] - pa[0], pb[2] - pa[2]
    m = math.hypot(dx, dz)
    th = None
    if m > 1e-4:
        hw = ww * 0.5
        nx, nz = -dz / m * hw, dx / m * hw
        mx, my, mz = (pa[0] + pb[0]) * 0.5, (pa[1] + pb[1]) * 0.5, (pa[2] + pb[2]) * 0.5
        lx, ly, ls = cam.project(mx + nx, my, mz + nz)
        rx, ry, rs = cam.project(mx - nx, my, mz - nz)
        if lx is not None and rx is not None and ls > 0 and rs > 0:
            sepx, sepy = (lx - rx) / cam.ui_kx, ly - ry
            ux, uy = (bx - ax) / cam.ui_kx, by - ay
            ul = math.hypot(ux, uy)
            if ul > 1e-4:
                th = abs(sepx * (-uy / ul) + sepy * (ux / ul))
            else:
                th = math.hypot(sepx, sepy)
    if th is None:
        return wmin
    return max(wmin, min(cap, th))


def place_strip(cv, tex, R, ax, ay, bx, by, th, a, rgb, kx, exact=True, over=0.0,
                joint="full"):
    """Port of IqmCards:place_strip -- the body, and the halo copy behind it.

    `joint` is the preview's own knob and has no counterpart in the game yet. The
    shipped rule is `len + th`: extend every strip by a full thickness so consecutive
    segments overlap by half a width at each end and a bend cannot leave an open wedge
    on the outside of the turn. That is sized against the THICKNESS and takes no account
    of the segment's LENGTH -- and at the near end, where a segment is about a metre of
    ground and the stroke is 60-90 px thick, the extension is as long as the segment
    itself. Every other band then gets painted twice (brighter body, and the later
    segment's black halo over the earlier body), which is the ladder this tool made
    visible.

      full   -- the shipped rule, len + th
      capped -- len + min(th, len * JOINT_FRAC): the same overlap wherever it is small
                relative to the segment, clamped where it is not
      none   -- exact length, to see the wedges the overlap exists to close
    """
    dxk, dy = (bx - ax) / kx, by - ay
    ln = max(1e-4, math.hypot(dxk, dy))
    ang = math.atan2(-dy, dxk)
    mx, my = (ax + bx) * 0.5, (ay + by) * 0.5
    if exact or joint == "none":
        length = ln
    elif joint == "capped":
        length = ln + min(th, ln * JOINT_FRAC)
    else:
        length = ln + th
    if over > 0:
        length += over
        h = over * 0.5 / ln
        mx -= (bx - ax) * h
        my -= dy * h
    edge = min(R["EDGE_MAX"], max(R["EDGE_MIN"], th * R["EDGE"]))
    cv.blit(tex, mx, my, length, th + edge * 2, ang, (int(a * R["SHA"]), 0, 0, 0))
    cv.blit(tex, mx, my, length, th, ang, (int(a), rgb[0], rgb[1], rgb[2]))


def place_arms(cv, tex, R, cam, p, ux, uz, a, rgb):
    """Port of IqmCards:place_arms -- a chevron as two ground strips."""
    hl, hw = R["alen"] * 0.5, R["awide"] * 0.5
    nx, nz = -uz, ux
    t1 = (p[0] + ux * hl, p[1], p[2] + uz * hl)
    tx, ty, ts = cam.project(*t1)
    if tx is None or ts <= 0:
        return
    bx0, bz0 = p[0] - ux * hl, p[2] - uz * hl
    for s in (-1, 1):
        t2 = (bx0 + nx * hw * s, p[1], bz0 + nz * hw * s)
        ex, ey, es = cam.project(*t2)
        if ex is None or es <= 0:
            continue
        th = seg_width(cam, t1, t2, tx, ty, ex, ey, R["aw"], R["WMIN"], R["WMAX"])
        place_strip(cv, tex, R, tx, ty, ex, ey, th, a, rgb, cam.ui_kx, exact=True)


def place_mark(cv, tex, R, cam, p, ux, uz, a, rgb, slices=1, shape="chevron", scale=1.0):
    """Port of IqmCards:place_mark -- the chevron as one quad, or as `slices` of one.

    A CUIStatic is always a rotated RECTANGLE; the true projection of the mark's ground
    footprint is a trapezoid. `slices` cuts the footprint across travel and fits each
    piece its own rectangle -- piecewise affine, so the keystone residual falls roughly
    as 1/N. The cost is that adjacent pieces measure their width at their OWN centres
    and so do not agree at the seam. --slices exists to see which is worse.
    """
    # Same box as build.mark_box() and IqmCards:place_mark -- for the chevron, out to the
    # arm's outer corners with L the true tip-to-corner length. shape_box holds all three.
    back, fwd, half = shape_box(shape, R)
    if scale != 1.0:
        back, fwd, half = back * scale, fwd * scale, half * scale
    nx, nz = -uz, ux
    span = back + fwd
    for k in range(slices):
        s0 = -back + span * k / slices
        s1 = -back + span * (k + 1) / slices
        sm = (s0 + s1) * 0.5
        t1 = (p[0] + ux * s0, p[1], p[2] + uz * s0)
        t2 = (p[0] + ux * s1, p[1], p[2] + uz * s1)
        ax, ay, as_ = cam.project(*t1)
        bx, by, bs = cam.project(*t2)
        if ax is None or bx is None or as_ <= 0 or bs <= 0:
            continue
        # THE RECT IS THE PIECE'S TWO PROJECTED AXES, each measured on its own (R2.28) --
        # not seg_width, which projects out the along-axis skew that for a mark IS the
        # shape. The across axis is measured at the piece's own centre, which is exactly
        # what makes neighbouring pieces disagree at the seam.
        cx_, cy_, cz_ = p[0] + ux * sm, p[1], p[2] + uz * sm
        lx, ly, ls = cam.project(cx_ + nx * half, cy_, cz_ + nz * half)
        rx, ry, rs = cam.project(cx_ - nx * half, cy_, cz_ - nz * half)
        dxk, dy = (bx - ax) / cam.ui_kx, by - ay
        ln = math.hypot(dxk, dy)
        cxk = None
        if lx is not None and rx is not None and ls > 0 and rs > 0:
            cxk, cyy = (lx - rx) / cam.ui_kx, ly - ry
            th = math.hypot(cxk, cyy)
        else:
            th = seg_width(cam, t1, t2, ax, ay, bx, by, half * 2, R["WMIN"], R["MCAP"])
        th = min(max(th, R["WMIN"]), R["MCAP"])
        if ln < 1e-4 and cxk is None:
            continue
        # The along axis keeps a floor in PIXELS (R2.30), the same kind of legibility
        # guard WMIN is for a stroke's thickness -- not a fraction of the artwork's
        # aspect, which bound the whole run to one shape and stopped it lying down into
        # the ground. Shared out between the pieces, so N of them floor where one did.
        if ln < R["MLMIN"] / slices:
            ln = R["MLMIN"] / slices
        # The angle from BOTH axes, weighted by how long each projects (R2.28).
        if cxk is not None:
            w1 = dxk * dxk + dy * dy
            w2 = cxk * cxk + cyy * cyy
            a1 = math.atan2(-dy, dxk)
            a2 = math.atan2(-cyy, cxk) - math.pi * 0.5
            if math.cos(a1 - a2) < 0:
                w1 = 0.0
            ang = math.atan2(w1 * math.sin(a1) + w2 * math.sin(a2),
                             w1 * math.cos(a1) + w2 * math.cos(a2))
        else:
            ang = math.atan2(-dy, dxk)
        mx, my = (ax + bx) * 0.5, (ay + by) * 0.5
        # The texture's WIDTH axis is along travel (build.mark_box maps image x to X),
        # so a piece takes the matching vertical band of the artwork -- SetTextureRect
        # in the game, a crop here.
        sub = tex
        if slices > 1:
            w = tex.size[0]
            sub = tex.crop((int(round(w * k / slices)), 0,
                            int(round(w * (k + 1) / slices)), tex.size[1]))
        # No backing copy since R2.26b -- the keyline is baked into the artwork. See the
        # note in IqmCards:place_mark for why a scaled copy could never be concentric.
        cv.blit(sub, mx, my, ln, th, ang, (int(a), rgb[0], rgb[1], rgb[2]))


# --------------------------------------------------------------------------
# The floor
# --------------------------------------------------------------------------
def ground(cam, w, h, seed=7):
    """Procedural concrete, with a pale patch and a dark one.

    Not decoration: the route's legibility problem is contrast against ground it does
    not control, and a flat grey backdrop flatters a washed-out stroke in a way real
    ground does not. Drawn in WORLD space and projected, so the texture recedes with
    the same perspective the route does and near marks are judged against near ground.
    """
    import random
    rnd = random.Random(seed)
    img = Image.new("RGBA", (w, h), (44, 46, 48, 255))
    dr = ImageDraw.Draw(img)
    # sky/horizon wash above the horizon line
    hz = cam.project(1e5, 0.0, 0.0)[1] or 0
    dr.rectangle([0, 0, w, max(0, int(hz * h / UI_H))], fill=(64, 68, 72, 255))

    def put(x, z, size, col):
        ux, uy, d = cam.project(x, 0.0, z)
        if ux is None or d <= 0.5:
            return
        r = max(1.0, size * 380 / d)
        dr.ellipse([ux * w / UI_W - r, uy * h / UI_H - r * 0.35,
                    ux * w / UI_W + r, uy * h / UI_H + r * 0.35], fill=col)

    # Broad tonal variation first, then grit on top of it. Kept low-contrast and
    # small-featured: the backdrop must not compete with the thing being judged, and a
    # blotchy one makes every stroke look crisper than it is by comparison.
    for _ in range(900):
        x = rnd.uniform(0.5, 80.0)
        z = rnd.uniform(-30.0, 30.0)
        v = rnd.randint(46, 60)
        put(x, z, rnd.uniform(0.35, 1.1), (v, v - 1, v - 3, 255))
    # A deliberately PALE stretch and a deliberately DARK one, across the path. The route
    # has to stay readable on both, and a uniform mid-grey never asks it to.
    for _ in range(1400):
        x = rnd.uniform(9.0, 19.0)
        z = rnd.uniform(-7.0, 7.0)
        v = rnd.randint(88, 104)
        put(x, z, rnd.uniform(0.25, 0.6), (v, v - 1, v - 6, 255))
    for _ in range(1400):
        x = rnd.uniform(26.0, 40.0)
        z = rnd.uniform(-7.0, 7.0)
        v = rnd.randint(24, 34)
        put(x, z, rnd.uniform(0.25, 0.6), (v, v, v + 1, 255))
    for _ in range(4200):
        x = rnd.uniform(0.3, 90.0)
        z = rnd.uniform(-25.0, 25.0)
        v = rnd.randint(30, 92)
        put(x, z, rnd.uniform(0.03, 0.14), (v, v, v - 3, 255))
    return img.filter(ImageFilter.GaussianBlur(0.7))


# --------------------------------------------------------------------------
# One frame
# --------------------------------------------------------------------------
def render(cfg, R, nav, bp, out_w, out_h):
    cam = Camera(eye=(0.0, 1.6, getattr(cfg, 'strafe', 0.0) or 0.0),
                 pitch_deg=cfg.pitch, vfov_deg=cfg.fov, out_w=out_w, out_h=out_h)
    path = scene_path(cfg.scene, nav["PATH_STEP"], nav["ARROW_LIFT"])
    verts, vs, chevs, cs = build_draw_list(path, cam, nav, cfg.dist, cfg.gap,
                                          half_phase=getattr(cfg, 'half_phase', False))

    base = ground(cam, out_w, out_h)
    cv = Canvas(base)

    # The two style predicates draw_route uses, same names, same membership.
    glyph_style = cfg.style in ("glyph", "marks")
    strokeless = cfg.style in ("arrows", "marks") or cfg.no_stroke

    strip = tex_strip(bp, cfg.feather)
    arm = tex_strip(bp, cfg.feather, tip=cfg.arm_tip, tail=cfg.arm_tail)
    # The glyph's SHAPE lives in the artwork while its BOX lives in RTE, and build.py says
    # of its MARK_* constants: "These four mirror RTE.alen / awide / aw ... Change one,
    # change both -- a mismatch shows up as the glyph sitting slightly off its own box."
    # Nothing enforces that in the mod, and here it would be worse than unenforced: an
    # --aw sweep would move the box while the picture stayed put, so every panel would be
    # answering a different question from the one asked. So the rule is applied.
    bp.MARK_LEN, bp.MARK_WIDE, bp.MARK_ARM = R["alen"], R["awide"], R["aw"]
    bp.MARK_TAIL = cfg.arm_tail
    shape = getattr(cfg, 'shape', 'chevron')
    if not glyph_style:
        mark = None
    elif shape == 'chevron':
        R["SPAD"] = 0.0
        mark = tex_mark_look(bp, R, cfg.feather,
                             wear=getattr(cfg, 'wear', 0.0) or 0.0,
                             rim=getattr(cfg, 'rim', None),
                             rim_ink=getattr(cfg, 'rim_ink', 0.0) or 0.0,
                             body_ink=getattr(cfg, 'body_ink', 1.0) or 1.0,
                             shadow=getattr(cfg, 'shadow', 0.0) or 0.0,
                             seed=int(getattr(cfg, 'seed', 11) or 11))
    else:
        mark = tex_shape(shape, R, cfg.feather)

    rgb = (int(R.get("route_r", R["r"])), int(R.get("route_g", 196)),
           int(R.get("route_b", 124)))
    if cfg.colour:
        rgb = cfg.colour
    alpha = cfg.alpha

    # Project every vertex once, as draw_route does.
    sx, sy, sd = [], [], []
    for p in verts:
        x, y, d = cam.project(*p)
        sx.append(x)
        sy.append(y)
        sd.append(cam.dist(*p) if x is not None else None)
    drawn = [d for d in sd if d is not None]
    d0 = min(drawn) if drawn else 0.0

    def fade_at(idx, n, d):
        """The two-ended fade: TAIL by position in the run, HEAD/HMIN by camera distance."""
        t = (idx - 1) / (n - 1) if n > 1 else 0.0
        if t > R["FADE"]:
            return 1 - (t - R["FADE"]) / (1 - R["FADE"]) * (1 - R["TAIL"])
        near = ((d if d is not None else 1e9) - d0) / cfg.head
        return cfg.hmin + (1 - cfg.hmin) * max(0.0, near) if near < 1 else 1.0

    n = len(verts)
    for k in range(len(chevs) - 1, -1, -1):
        p, ux, uz, vi = chevs[k]
        cd = cam.dist(*p)
        t = (k) / len(chevs) if len(chevs) > 1 else 0.0
        if t > R["FADE"]:
            f = 1 - (t - R["FADE"]) / (1 - R["FADE"]) * (1 - R["TAIL"])
        else:
            near = (cd - d0) / cfg.head
            f = cfg.hmin + (1 - cfg.hmin) * max(0.0, near) if near < 1 else 1.0
        # THE NEAR CUT-OFF, which this tool did not reproduce until R2.33c -- so it drew
        # marks at the player's feet that the game refuses to draw, and any question about
        # the near field got a confidently wrong answer. Exactly the class of drift the
        # header warns about, in the one constant the near field is entirely about.
        mnear = getattr(cfg, 'mnear', None)
        mnear = R["MNEAR"] if mnear is None else mnear
        mfade = getattr(cfg, 'mfade', None)
        mfade = R["MFADE"] if mfade is None else mfade
        if cd < mnear:
            f = 0.0
        elif cd < mnear + mfade:
            f *= (cd - mnear) / mfade
        # The near TAPER (preview only): shrink the glyph as it approaches, so the
        # footprint spans less depth exactly where the affine fit is worst. 1.0 = off.
        tmin = getattr(cfg, 'taper', 1.0) or 1.0
        sc = 1.0
        if tmin < 1.0:
            u = max(0.0, min(1.0, (cd - mnear) / max(1e-6, 5.0 - mnear)))
            sc = tmin + (1 - tmin) * u
        a = alpha * f
        if True:
            place_mark(cv, mark, R, cam, p, ux, uz, a, rgb, slices=int(getattr(cfg, 'slices', 1) or 1),
                       shape=getattr(cfg, 'shape', 'chevron'), scale=sc)
        else:
            place_arms(cv, arm, R, cam, p, ux, uz, a, rgb)

    return base.convert("RGB")


def label(img, text, sub=""):
    dr = ImageDraw.Draw(img)
    dr.rectangle([0, 0, img.size[0], 46], fill=(16, 16, 18))
    dr.text((12, 8), text, fill=(230, 230, 220))
    if sub:
        dr.text((12, 26), sub, fill=(150, 150, 145))
    return img


class Cfg:
    pass


def main():
    R = parse_rte()
    nav = parse_nav()
    bp = load_builder()

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    # One style left in the mod (R2.26c), so one style here.
    ap.add_argument("--style", default="marks", choices=["marks"])
    ap.add_argument("--scene", default="straight",
                    choices=["straight", "bend", "curve"])
    ap.add_argument("--out", default=os.path.join(HERE, "preview.png"))
    ap.add_argument("--width", type=int, default=1280)
    ap.add_argument("--height", type=int, default=720)
    ap.add_argument("--fov", type=float, default=55.0, help="vertical FOV, degrees")
    ap.add_argument("--pitch", type=float, default=-12.0, help="camera pitch, degrees")
    ap.add_argument("--dist", type=float, default=50.0, help="metres drawn (route_dist)")
    ap.add_argument("--gap", type=float, default=None, help="chevron spacing, m")
    ap.add_argument("--alpha", type=float, default=None, help="route_a, 0-255")
    ap.add_argument("--colour", default=None, help="r,g,b")
    ap.add_argument("--feather", type=float, default=None, help="build.py FEATHER")
    ap.add_argument("--arm-tip", type=float, default=None)
    ap.add_argument("--arm-tail", type=float, default=None)
    ap.add_argument("--head", type=float, default=None, help="RTE.HEAD, m")
    ap.add_argument("--hmin", type=float, default=None, help="RTE.HMIN, 0-1")
    ap.add_argument("--edge", type=float, default=None, help="RTE.EDGE")
    ap.add_argument("--sha", type=float, default=None, help="RTE.SHA")
    # Chevron geometry, in METRES of ground -- the same currency RTE uses, because these
    # are drawn by the measured-thickness machinery and a px figure would mean nothing.
    ap.add_argument("--aw", type=float, default=None, help="arm thickness, m (RTE.aw)")
    ap.add_argument("--alen", type=float, default=None, help="tip to back, m (RTE.alen)")
    ap.add_argument("--awide", type=float, default=None, help="tip to tip, m (RTE.awide)")
    ap.add_argument("--sweep", default=None,
                    help="KEY=v1,v2,v3 -- render one panel per value, labelled. KEY is "
                         "any RTE constant (aw, alen, awide, EDGE, SHA) or any preview "
                         "knob (feather, arm_tail, hmin, head, alpha, gap)")
    # Draw the marks without the stroke, in a style that normally has one. There is no
    # such route_style in the mod: `arrows` is the only strokeless design and it is fixed
    # to the two-quad chevron. Trying the combination HERE is the cheap way to find out
    # whether a fifth style would be worth the code (see IqmCards:draw_route, first_seg).
    ap.add_argument("--no-stroke", action="store_true",
                    help="suppress the stroke, whatever the style draws by default")
    ap.add_argument("--joint", default="full", choices=["full", "capped", "none"],
                    help="segment joint overlap rule; see place_strip")
    ap.add_argument("--compare", action="store_true",
                    help="render the current look beside a sharpened proposal")
    # The four look proposals (R2.33). All texture-side, all preview-only until picked.
    ap.add_argument("--wear", type=float, default=0.0,
                    help="break the interior up, 0 (flat, shipped) .. 1 (heavily worn)")
    ap.add_argument("--rim", type=float, default=None,
                    help="MARK_RIM, the baked keyline, as a fraction of arm thickness")
    ap.add_argument("--rim-ink", dest="rim_ink", type=float, default=0.0,
                    help="the rim's ink floor: 0 is black (shipped), 0.35 a dark tint")
    ap.add_argument("--body-ink", dest="body_ink", type=float, default=1.0,
                    help="the interior's ink: 1.0 is full colour (shipped), 0.78 sinks "
                         "the body so the rim reads as a BRIGHT edge instead of a dark one")
    ap.add_argument("--shadow", type=float, default=0.0,
                    help="baked contact shadow outside the outline, 0..1 alpha")
    ap.add_argument("--seed", type=int, default=11, help="wear pattern seed")
    ap.add_argument("--mnear", type=float, default=None,
                    help="near cut-off, m (RTE.MNEAR)")
    ap.add_argument("--mfade", type=float, default=None,
                    help="ramp above the cut-off, m (RTE.MFADE)")
    ap.add_argument("--half-phase", dest="half_phase", action="store_true",
                    help="one extra mark at half a gap, to fill the near hole")
    ap.add_argument("--taper", type=float, default=1.0,
                    help="shrink near marks to this fraction at the cut-off; 1 = off")
    ap.add_argument("--strafe", type=float, default=0.0,
                    help="slide the camera sideways off the route, metres -- the view the "
                         "keystone residual is judged in")
    ap.add_argument("--shape", choices=("chevron", "arrow", "bar", "disc", "square"), default="chevron",
                    help="candidate glyph shape; preview only, ships nothing")
    ap.add_argument("--slices", type=int, default=1,
                    help="cut each mark into N quads across travel (keystone test)")
    ap.add_argument("--dump", action="store_true", help="print constants and exit")
    args = ap.parse_args()

    for key in ("aw", "alen", "awide"):
        v = getattr(args, key)
        if v is not None:
            R[key] = v

    if args.dump:
        print("-- RTE (iqm_core.script) --")
        for k in sorted(R):
            print("   %-10s %s" % (k, R[k]))
        print("-- iqm_nav.script --")
        for k in NAV_KEYS:
            print("   %-10s %s" % (k, nav[k]))
        print("-- tools/stroke-tex/build.py --")
        for k in ("FEATHER", "ARM_TIP", "ARM_TAIL", "MARK_LEN", "MARK_WIDE", "MARK_ARM"):
            print("   %-10s %s" % (k, bp.SHIPPED.get(k, getattr(bp, k))))
        return 0

    def cfg_from(overrides=None):
        c = Cfg()
        c.style, c.scene = args.style, args.scene
        c.fov, c.pitch, c.dist = args.fov, args.pitch, args.dist
        c.gap = args.gap if args.gap is not None else (
            10.0 if args.style == "classic" else R.get("route_gap", 3.0))
        c.alpha = args.alpha if args.alpha is not None else R.get("route_a", R["a"])
        c.feather = args.feather if args.feather is not None else bp.SHIPPED["FEATHER"]
        c.arm_tip = args.arm_tip if args.arm_tip is not None else bp.SHIPPED["ARM_TIP"]
        c.arm_tail = args.arm_tail if args.arm_tail is not None else bp.SHIPPED["ARM_TAIL"]
        c.head = args.head if args.head is not None else R["HEAD"]
        c.hmin = args.hmin if args.hmin is not None else R["HMIN"]
        c.joint = args.joint
        c.no_stroke = args.no_stroke
        # These two must be copied here like everything else. cfg_from is the ONLY route
        # from argv into a render; a flag that only --sweep sets reaches render() as its
        # getattr default, so `--shape arrow` silently draws a chevron.
        c.shape = args.shape
        c.slices = args.slices
        c.strafe = args.strafe
        c.mnear, c.mfade = args.mnear, args.mfade
        c.half_phase, c.taper = args.half_phase, args.taper
        c.wear, c.rim, c.rim_ink = args.wear, args.rim, args.rim_ink
        c.body_ink = args.body_ink
        c.shadow, c.seed = args.shadow, args.seed
        c.colour = None
        if args.colour:
            c.colour = tuple(int(v) for v in args.colour.split(","))
        for k, v in (overrides or {}).items():
            setattr(c, k, v)
        return c

    if args.sweep:
        # One panel per value of one constant, on identical ground. The whole reason the
        # tool exists is that a look question is a COMPARISON, and a comparison held in
        # memory across two game sessions is not one.
        key, _, vals = args.sweep.partition("=")
        key = key.strip()
        # Numeric where it can be, verbatim where it cannot -- --sweep shape=chevron,bar
        # is as much a comparison as --sweep alen=0.5,0.68, and the sheet is the answer
        # to both.
        def _val(v):
            try:
                return float(v)
            except ValueError:
                return v.strip()
        values = [_val(v) for v in vals.split(",") if v.strip()]
        if not values:
            raise SystemExit("preview: --sweep needs KEY=v1,v2,...")
        w, h = args.width, args.height
        panels = []
        for v in values:
            Rv = dict(R)
            if key in Rv:
                Rv[key] = v
                cfg = cfg_from()
            else:
                cfg = cfg_from({key: v})
            img = render(cfg, Rv, nav, bp, w, h)
            label(img, "%s = %s" % (key, ("%g" % v) if isinstance(v, float) else v),
                  "style %s   pitch %g   gap %gm" % (args.style, args.pitch, cfg.gap))
            panels.append(img)
        sheet = Image.new("RGB", (w * len(panels) + 8 * (len(panels) - 1), h), (16, 16, 18))
        for i, im in enumerate(panels):
            sheet.paste(im, (i * (w + 8), 0))
        sheet.save(args.out)
        print("wrote", args.out, sheet.size)
        return 0

    if args.compare:
        # The proposal from the session's analysis, all in one place so the picture and
        # the recommendation cannot drift apart. Everything here is a candidate, not a
        # decision -- which is the point of rendering it beside the current look.
        sharp = {"feather": 0.04, "arm_tail": 0.20, "hmin": 0.75, "head": 1.5,
                 "alpha": 255.0, "edge": 0.10, "sha": 0.75}
        w, h = args.width, args.height
        left = render(cfg_from(), R, nav, bp, w, h)
        R2 = dict(R)
        R2["EDGE"], R2["SHA"] = sharp["edge"], sharp["sha"]
        right = render(cfg_from(sharp), R2, nav, bp, w, h)
        label(left, "CURRENT",
              "feather %.2f  HMIN %.2f  HEAD %.1fm  alpha %d  EDGE %.2f"
              % (bp.SHIPPED["FEATHER"], R["HMIN"], R["HEAD"],
                 R.get("route_a", R["a"]), R["EDGE"]))
        label(right, "SHARPENED (proposal)",
              "feather %.2f  HMIN %.2f  HEAD %.1fm  alpha %d  EDGE %.2f"
              % (sharp["feather"], sharp["hmin"], sharp["head"], sharp["alpha"],
                 sharp["edge"]))
        sheet = Image.new("RGB", (w * 2 + 12, h), (16, 16, 18))
        sheet.paste(left, (0, 0))
        sheet.paste(right, (w + 12, 0))
        sheet.save(args.out)
        print("wrote", args.out, sheet.size)
        return 0

    img = render(cfg_from(), R, nav, bp, args.width, args.height)
    img.save(args.out)
    print("wrote", args.out, img.size)
    return 0


if __name__ == "__main__":
    sys.exit(main())
